// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreatTraderApi.Data;

#nullable disable

namespace TreatTraderApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108003435_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("TreatTraderApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nutrition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "japan",
                            Desc = "來自靜岡的濃郁抹茶香，口感綿密。",
                            Img = "Matcha.jpg",
                            Name = "日本靜岡抹茶蛋糕",
                            Nutrition = "熱量: 350大卡 | 蛋白質: 5g",
                            Price = 350
                        },
                        new
                        {
                            Id = 2,
                            Category = "usa",
                            Desc = "美式經典，外酥內軟，巧克力豆爆漿。",
                            Img = "Cookie.jpg",
                            Name = "美國重磅巧克力餅乾",
                            Nutrition = "熱量: 450大卡 | 糖: 30g",
                            Price = 150
                        },
                        new
                        {
                            Id = 3,
                            Category = "france",
                            Desc = "法式浪漫，甜而不膩，少女心爆發。",
                            Img = "Macaron.jpg",
                            Name = "法國巴黎馬卡龍",
                            Nutrition = "熱量: 200大卡 | 糖: 40g",
                            Price = 450
                        },
                        new
                        {
                            Id = 4,
                            Category = "uk",
                            Desc = "下午茶首選，優雅茶香。",
                            Img = "TeaBiscuit.jpg",
                            Name = "英國皇家伯爵茶餅",
                            Nutrition = "熱量: 150大卡 | 脂肪: 10g",
                            Price = 280
                        },
                        new
                        {
                            Id = 5,
                            Category = "korea",
                            Desc = "鹹甜交織，起司控最愛。",
                            Img = "Cheese.jpg",
                            Name = "韓國起司夾心餅",
                            Nutrition = "熱量: 300大卡 | 鈉: 200mg",
                            Price = 120
                        },
                        new
                        {
                            Id = 6,
                            Category = "japan",
                            Desc = "北海道經典伴手禮。",
                            Img = "WhiteLover.jpg",
                            Name = "日本白色戀人",
                            Nutrition = "熱量: 250大卡 | 糖: 15g",
                            Price = 480
                        },
                        new
                        {
                            Id = 7,
                            Category = "usa",
                            Desc = "重乳酪風味，濃郁化口。",
                            Img = "CheeseCake.jpg",
                            Name = "紐約起司蛋糕",
                            Nutrition = "熱量: 400大卡 | 脂肪: 25g",
                            Price = 320
                        },
                        new
                        {
                            Id = 8,
                            Category = "france",
                            Desc = "酸甜清爽，法式甜點代表。",
                            Img = "LemonTart.jpg",
                            Name = "法國檸檬塔",
                            Nutrition = "熱量: 220大卡 | 糖: 18g",
                            Price = 160
                        },
                        new
                        {
                            Id = 9,
                            Category = "germany",
                            Desc = "酒漬櫻桃與巧克力的完美結合。",
                            Img = "Cake.jpg",
                            Name = "德國黑森林蛋糕",
                            Nutrition = "熱量: 450大卡 | 酒精: 微量",
                            Price = 500
                        },
                        new
                        {
                            Id = 10,
                            Category = "italy",
                            Desc = "帶我走，享受微醺的咖啡香。",
                            Img = "Tiramisu.jpg",
                            Name = "義大利提拉米蘇",
                            Nutrition = "熱量: 380大卡 | 咖啡因: 有",
                            Price = 380
                        },
                        new
                        {
                            Id = 11,
                            Category = "belgium",
                            Desc = "頂級可可，絲滑柔順。",
                            Img = "Choco.jpg",
                            Name = "比利時巧克力",
                            Nutrition = "熱量: 550大卡 | 可可脂: 高",
                            Price = 250
                        },
                        new
                        {
                            Id = 12,
                            Category = "taiwan",
                            Desc = "在地土鳳梨，酸甜適中。",
                            Img = "Pineapple.jpg",
                            Name = "台灣鳳梨酥",
                            Nutrition = "熱量: 180大卡 | 纖維: 2g",
                            Price = 200
                        });
                });

            modelBuilder.Entity("TreatTraderApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TreatTraderApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TreatTraderApi.Models.Review", b =>
                {
                    b.HasOne("TreatTraderApi.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreatTraderApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TreatTraderApi.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
